---
- hosts: all
  remote_user: "{{user}}"
  vars:
    hadoop_version: 2.7.3
    hadoop_dir: "/home/{{user}}/hadoop-{{hadoop_version}}"

  tasks:
 # - debug: var=hostvars[]['hostname']
  - name: install programs
    apt: name={{item}} state=present update_cache=true
    become: yes
    with_items: 
      - openssh-server
      - postgresql-contrib
      - default-jdk
      - default-jre
      
  - name: extract hadoop folder
    unarchive: src="templates/hadoop-{{hadoop_version}}.tar.gz" dest="/home/{{user}}/"
    
  - name: copy templates over
    template: src="templates/{{item.src}}" dest="{{item.dest}}"
    become: yes
    with_items:
      - { src: core-site.xml.j2, dest: "{{hadoop_dir}}/etc/hadoop/core-site.xml" }
      - { src: hdfs-site.xml.j2, dest: "{{hadoop_dir}}/etc/hadoop/hdfs-site.xml" }
      - { src: yarn-site.xml.j2, dest: "{{hadoop_dir}}/etc/hadoop/yarn-site.xml" }
      - { src: mapred-site.xml.j2, dest: "{{hadoop_dir}}/etc/hadoop/mapred-site.xml" }
      - { src: slaves.j2, dest: "{{hadoop_dir}}/etc/hadoop/slaves" }
      - { src: etc-hosts.j2, dest: /etc/hosts }