---
- hosts: all
  remote_user: "{{user}}"
  vars:
    hadoop_version: 2.7.3
    hive_version: 2.1.1
    hadoop_dir: "/home/{{user}}/hadoop-{{hadoop_version}}"
    hive_dir: "{{hadoop_dir}}/apache-hive-{{hive_version}}-bin"
    java_home: "/usr/lib/jvm/default-java"

  tasks:
 # - debug: var=hostvars[]['hostname']
  - name: install programs
    apt: name={{item}} state=present update_cache=true
    become: yes
    with_items: 
      - openssh-server
      - postgresql-contrib
      - default-jdk
      - default-jre
      
  - name: add JAVA_HOME
    lineinfile: dest=/etc/environment
                regexp="JAVA_HOME={{java_home}}"
                line="JAVA_HOME={{java_home}}"
    become: yes
    
  - name: download hadoop locally
    run_once: true
    local_action:
      get_url
      url="http://mirrors.ukfast.co.uk/sites/ftp.apache.org/hadoop/common/hadoop-{{hadoop_version}}/hadoop-{{hadoop_version}}.tar.gz"
      dest="/home/{{user}}/"
      
  - name: download hive locally
    run_once: true
    local_action:
      get_url
      url="http://apache.mirror.anlx.net/hive/hive-{{hive_version}}/apache-hive-{{hive_version}}-bin.tar.gz"
      dest="/home/{{user}}/"
      
  - name: download and extract hadoop folder
    unarchive: 
      src: "/home/{{user}}/hadoop-{{hadoop_version}}.tar.gz"
      dest: "/home/{{user}}/"
      remote_src: False
      mode: 0777
      owner: "{{user}}"
      
  - name: download and extract hive folder
    unarchive: 
      src: "/home/{{user}}/apache-hive-{{hive_version}}-bin.tar.gz"
      dest: "{{hadoop_dir}}"
      remote_src: False
      mode: 0777
      owner: "{{user}}"
    
  - name: copy templates over
    template: src="templates/{{item.src}}" dest="{{item.dest}}"
    become: yes
    with_items:
      - { src: core-site.xml.j2, dest: "{{hadoop_dir}}/etc/hadoop/core-site.xml" }
      - { src: hdfs-site.xml.j2, dest: "{{hadoop_dir}}/etc/hadoop/hdfs-site.xml" }
      - { src: yarn-site.xml.j2, dest: "{{hadoop_dir}}/etc/hadoop/yarn-site.xml" }
      - { src: mapred-site.xml.j2, dest: "{{hadoop_dir}}/etc/hadoop/mapred-site.xml" }
      - { src: slaves.j2, dest: "{{hadoop_dir}}/etc/hadoop/slaves" }
      - { src: etc-hosts.j2, dest: /etc/hosts }
      - { src: hive-env.sh.j2, dest: "{{hive_dir}}/conf/hive-env.sh" }
      - { src: hive-site.xml.j2, dest: "{{hive_dir}}/conf/hive-site.xml" }
      
  - name: change hostname
    hostname: name="{{hostname}}"
    become: yes
      
  - name: reboot everything
    shell: reboot
    become: yes
    when: inventory_hostname in groups['slaves']